#!/usr/bin/env sh
# =============================================================================
# ADNFLIX Production Deploy - Docker
# Fill in the CONFIG section below and run: ./deploy.sh
# =============================================================================

set -e

# Use sudo for compose when the user is not yet in the docker group (e.g. right after CI install).
run_dc() {
  if docker info >/dev/null 2>&1; then
    docker compose "$@"
  elif sudo -n docker info >/dev/null 2>&1; then
    sudo -n docker compose "$@"
  else
    docker compose "$@"
  fi
}

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: docker not found. Install Docker Engine + Compose plugin first (see DEPLOY-VPS.md Step 2)."
  exit 1
fi
if ! run_dc version >/dev/null 2>&1; then
  echo "ERROR: docker compose (v2) not found. Install docker-compose-plugin (e.g. apt install docker-compose-plugin)."
  exit 1
fi

# -----------------------------------------------------------------------------
# CONFIG - Edit these for your production
# -----------------------------------------------------------------------------
DOMAIN="${ADNFLIX_DOMAIN:-coliningram.site}"
FRONTEND_URL="${ADNFLIX_FRONTEND_URL:-http://${DOMAIN}}"
BACKEND_URL="${ADNFLIX_BACKEND_URL:-http://api.${DOMAIN}}"

# Secrets (min 32 chars for JWT and SESSION). Generate with:
#   openssl rand -base64 48
JWT_SECRET="${ADNFLIX_JWT_SECRET:-CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS}"
SESSION_SECRET="${ADNFLIX_SESSION_SECRET:-CHANGE_ME_TO_A_LONG_RANDOM_SESSION_SECRET_32_CHARS}"

# MySQL (used by db service and backend)
MYSQL_PASSWORD="${ADNFLIX_MYSQL_PASSWORD:-adnflix_password_change_me}"
MYSQL_ROOT_PASSWORD="${ADNFLIX_MYSQL_ROOT_PASSWORD:-root_password_change_me}"

# CORS origins (comma-separated; backend will allow these)
CORS_ORIGINS="${ADNFLIX_CORS_ORIGINS:-http://localhost,http://127.0.0.1,http://${DOMAIN},http://www.${DOMAIN}}"

# -----------------------------------------------------------------------------
# Deploy
# -----------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo ">>> ADNFLIX Docker production deploy"
echo ">>> Domain: $DOMAIN"
echo ""

# Write .env for docker-compose variable substitution
cat > .env << EOF
# Generated by deploy.sh - do not commit (add .env to .gitignore)
ADNFLIX_DOMAIN=$DOMAIN
ADNFLIX_JWT_SECRET=$JWT_SECRET
ADNFLIX_SESSION_SECRET=$SESSION_SECRET
ADNFLIX_MYSQL_PASSWORD=$MYSQL_PASSWORD
ADNFLIX_MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
ADNFLIX_CORS_ORIGINS=$CORS_ORIGINS
EOF

# Ensure video storage exists
mkdir -p storage/videos

# Build and start
echo ">>> Building and starting containers..."
run_dc --env-file .env up -d --build

echo ""
echo ">>> Deploy finished."
echo ""
echo "  Frontend:  $FRONTEND_URL"
echo "  Backend:   $BACKEND_URL"
echo "  Health:    ${BACKEND_URL}/health"
echo ""
echo "  Default admin: username=admin, password=admin (change after first login)"
echo "  Video files:    ./storage/videos (persisted on host)"
echo ""
